# Generated by Django 3.0.2 on 2020-01-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0003_remove_languages_reference_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mdp_props', to='mdp.MathJaxFormulas'),
        ),
        migrations.DeleteModel(
            name='MDPProps',
        ),
    ]
