# Generated by Django 3.0.2 on 2020-01-06 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0006_auto_20200106_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targ_space', to='mdp.MathJaxFormulas'),
        ),
    ]
