# Generated by Django 3.0.2 on 2020-01-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0007_auto_20200106_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitymeasure',
            name='best',
            field=models.CharField(choices=[(0, '0'), (1, '1')], default=0, max_length=100),
        ),
    ]
