# Generated by Django 3.0.2 on 2020-01-07 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0009_auto_20200107_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitymeasure',
            name='correlation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correlation', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='dissimilarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dissimilarity', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='geometric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geometric', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='glob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glob', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='homology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homology', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='probability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probability', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='rangee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='range', to='mdp.MathJaxFormulas'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='set_difference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setdifference', to='mdp.QMParameters'),
        ),
    ]
