# Generated by Django 3.0.2 on 2020-01-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0010_auto_20200107_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targ_space', to='mdp.MathJaxFormulas'),
        ),
    ]
