# Generated by Django 3.0.2 on 2020-01-07 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0013_auto_20200107_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='best_mdp_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_mdp', to='mdp.BestMDP'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mdp_props', to='mdp.MDPProps'),
        ),
    ]
