# Generated by Django 3.0.2 on 2020-01-11 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0014_auto_20200107_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='enrichment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mdp.EnrichmentType'),
        ),
        migrations.AlterField(
            model_name='mathjaxformulas',
            name='equation_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eqntype', to='mdp.EqnTypes'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='cartesian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cartesian', to='mdp.HandlingAbility'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='categorical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categorical', to='mdp.HandlingAbility'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='complexity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdp.MathJaxFormulas', verbose_name='Complexity (MathJax)'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='dissimilarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dissimilarity', to='mdp.HandlingAbility'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='linearity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='linearity', to='mdp.HandlingAbility'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locality', to='mdp.HandlingAbility'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='multi_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='multi_level', to='mdp.HandlingAbility'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='ne_structures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ne_structures', to='mdp.HandlingAbility', verbose_name='Neighbouring Structures'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='ordinal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordinal', to='mdp.HandlingAbility'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='out_of_core_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='out_of_core_data', to='mdp.HandlingAbility'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='reference_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdp.Reference', verbose_name='Reference Paper'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='stability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stability', to='mdp.HandlingAbility'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='steerability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='steerability', to='mdp.HandlingAbility'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='supervision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervision', to='mdp.HandlingAbility'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='correlation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='correlation', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='dissimilarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dissimilarity', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='geometric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geometric', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='glob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='glob', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='homology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='homology', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='local', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='probability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='probability', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='rangee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='range', to='mdp.MathJaxFormulas'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rank', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='set_difference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='setdifference', to='mdp.QMParameters'),
        ),
        migrations.AlterField(
            model_name='task',
            name='best_mdp_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='best_mdp', to='mdp.BestMDP'),
        ),
        migrations.AlterField(
            model_name='task',
            name='input_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='input_space', to='mdp.MathJaxFormulas'),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='output_space', to='mdp.MathJaxFormulas'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdp.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reference_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdp.Reference'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mdp_props', to='mdp.MDPProps'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mdp.TaskType'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='targ_space', to='mdp.MathJaxFormulas'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='variant_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variant_ref', to='mdp.Reference'),
        ),
    ]
