# Generated by Django 3.0.2 on 2020-01-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0015_auto_20200110_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': 'Team Data - (Main)'},
        ),
        migrations.AlterModelOptions(
            name='bestmdp',
            options={'verbose_name_plural': 'Best Matching MDPs - (Supplementary)'},
        ),
        migrations.AlterModelOptions(
            name='enrichment',
            options={'verbose_name_plural': 'Enrichments - (Main)'},
        ),
        migrations.AlterModelOptions(
            name='enrichmenttype',
            options={'verbose_name_plural': 'Enrichment Type - (Supplementary)'},
        ),
        migrations.AlterModelOptions(
            name='eqntypes',
            options={'verbose_name_plural': 'Equation Types - (Supplementary)'},
        ),
        migrations.AlterModelOptions(
            name='handlingability',
            options={'verbose_name_plural': 'Handling Abilities - (Supplementary)'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name_plural': 'Programming Languages - (Supplementary)'},
        ),
        migrations.AlterModelOptions(
            name='mathjaxformulas',
            options={'verbose_name_plural': 'MathJax Formulae - (Supplementary)'},
        ),
        migrations.AlterModelOptions(
            name='mdp',
            options={'verbose_name_plural': 'Projection Techniques - (Main)'},
        ),
        migrations.AlterModelOptions(
            name='mdpprops',
            options={'verbose_name_plural': 'Technique Properties - (Supplementary)'},
        ),
        migrations.AlterModelOptions(
            name='mdpsforlang',
            options={'verbose_name': 'Language-Based MDP Handling', 'verbose_name_plural': 'Language-Based MDP Handling - (Main)'},
        ),
        migrations.AlterModelOptions(
            name='qmparameters',
            options={'verbose_name_plural': 'QM Parameters - (Supplementary)'},
        ),
        migrations.AlterModelOptions(
            name='qualitymeasure',
            options={'verbose_name_plural': 'Quality Measures - (Main)'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name_plural': 'References - (Supplementary)'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Tasks - (Main)'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'verbose_name_plural': 'Task Types - (Supplementary)'},
        ),
        migrations.AlterModelOptions(
            name='toolboxes',
            options={'verbose_name_plural': 'Toolboxes - (Supplementary)'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name_plural': 'Variants - (Supplementary)'},
        ),
    ]
