# Generated by Django 3.0.2 on 2020-01-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0016_auto_20200111_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': '(Main) - Team Data'},
        ),
        migrations.AlterModelOptions(
            name='bestmdp',
            options={'verbose_name_plural': '(Supplementary) - Best Matching MDPs'},
        ),
        migrations.AlterModelOptions(
            name='enrichment',
            options={'verbose_name_plural': '(Main) - Enrichments'},
        ),
        migrations.AlterModelOptions(
            name='enrichmenttype',
            options={'verbose_name_plural': '(Supplementary) - Enrichment Type'},
        ),
        migrations.AlterModelOptions(
            name='eqntypes',
            options={'verbose_name_plural': '(Supplementary) - Equation Types'},
        ),
        migrations.AlterModelOptions(
            name='handlingability',
            options={'verbose_name_plural': '(Supplementary) - Handling Abilities'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name_plural': '(Supplementary) - Programming Languages'},
        ),
        migrations.AlterModelOptions(
            name='mathjaxformulas',
            options={'verbose_name_plural': '(Supplementary) - MathJax Formulae'},
        ),
        migrations.AlterModelOptions(
            name='mdp',
            options={'verbose_name_plural': '(Main) - Projection Techniques'},
        ),
        migrations.AlterModelOptions(
            name='mdpprops',
            options={'verbose_name_plural': '(Supplementary) - Technique Properties'},
        ),
        migrations.AlterModelOptions(
            name='mdpsforlang',
            options={'verbose_name': 'Language-Based MDP Handling', 'verbose_name_plural': '(Main) - Language-Based MDP Handling'},
        ),
        migrations.AlterModelOptions(
            name='qmparameters',
            options={'verbose_name_plural': '(Supplementary) - QM Parameters'},
        ),
        migrations.AlterModelOptions(
            name='qualitymeasure',
            options={'verbose_name_plural': '(Main) - Quality Measures'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name_plural': '(Supplementary) - References'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': '(Main) - Tasks'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'verbose_name_plural': '(Supplementary) - Task Types'},
        ),
        migrations.AlterModelOptions(
            name='toolboxes',
            options={'verbose_name_plural': '(Supplementary) - Toolboxes'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name_plural': '(Supplementary) - Variants'},
        ),
    ]
