# Generated by Django 3.0.2 on 2020-01-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0017_auto_20200111_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdpsforlang',
            name='circle_list',
            field=models.ManyToManyField(related_name='toolboxes', to='mdp.Languages', verbose_name='Toolboxes List'),
        ),
        migrations.AlterField(
            model_name='mdpsforlang',
            name='square_list',
            field=models.ManyToManyField(related_name='libs', to='mdp.Languages', verbose_name='Libraries List'),
        ),
    ]
