# Generated by Django 3.0.2 on 2020-01-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0018_auto_20200113_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdpsforlang',
            name='reference_list',
            field=models.ManyToManyField(blank=True, max_length=300, to='mdp.Reference'),
        ),
    ]
