# Generated by Django 3.0.2 on 2020-01-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0019_auto_20200113_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdp',
            name='tech_variants',
            field=models.ManyToManyField(blank=True, related_name='variantstab', to='mdp.Variants'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='variant_refs',
            field=models.ManyToManyField(blank=True, related_name='mainvarref', to='mdp.Reference'),
        ),
        migrations.AlterField(
            model_name='mdpsforlang',
            name='circle_list',
            field=models.ManyToManyField(blank=True, related_name='toolboxes', to='mdp.Languages', verbose_name='Toolboxes List'),
        ),
        migrations.AlterField(
            model_name='mdpsforlang',
            name='square_list',
            field=models.ManyToManyField(blank=True, related_name='libs', to='mdp.Languages', verbose_name='Libraries List'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='reference',
            field=models.ManyToManyField(blank=True, to='mdp.Reference'),
        ),
        migrations.AlterField(
            model_name='task',
            name='child_id',
            field=models.ManyToManyField(blank=True, related_name='_task_child_id_+', to='mdp.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='numbers',
            field=models.ManyToManyField(blank=True, related_name='_task_numbers_+', to='mdp.Task', verbose_name='Number(s)'),
        ),
    ]
