# Generated by Django 3.0.2 on 2020-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0020_auto_20200113_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actor',
            field=models.CharField(choices=[('U', 'User'), ('M', 'Machine'), ('UnM', 'User and Machine')], default='U', max_length=100),
        ),
    ]
